### PR TITLE
PDFGenerator.java: fix measure numbers in exported PDF

### LINKED ISSUE #13: Fix measure numbers in exported PDF
The exported PDF assumes all measures are 4 counts, regardless of how it's set up in the application. This creates incorrect measure numbers in the drill PDF for time signatures != 4/4.

Instead, the `PDFGenerator` should use `DrillInfo.getCountsHashMap()` to calculate the correct measure numbers.

### PR DESCRIPTION
**Pull request by parker-rho**
Closes #13 

Uses DrillInfo.getCountsHashMap() to calculate the correct measure numbers instead of assuming 4 counts per measure. Still assumes a default of 4 counts per measure if the Song Constants aren't changed.

Unrelated: How do I request reviews on my PR's instead of manually @ing you @vdye?

### CODE REVIEW

File: src/main/java/org/bigredbands/mb/controllers/PDFGenerator.java [hunk 1]
```diff
@@ -123,9 +123,18 @@ public void createPDF(DrillInfo drillInfo, File file) throws IOException {
                     pageHeight - bufferTop);
             // we have a map of measure number to count per measure
             // currently assumes 4 counts per measure
-            // TODO: Make measures adjust with changes in count per measure
             begMeasure = endMeasure;
-            endMeasure = begMeasure + move.getCounts() / 4;
+            int totalCounts = 0;
+            int currentMeasure = begMeasure;
+            while (move.getCounts() > totalCounts){
```
Comment (vdye) [inline src/main/java/org/bigredbands/mb/controllers/PDFGenerator.java:129]: The `while` loop is probably the most readable way to implement this, albeit not the most efficient (it's `O(n)`, where `n` is the number of measures in the drill). That said, efficiency isn't a major concern here; at most, we'll have on the order of hundreds of measures in a single drill file - not enough to cause a noticeable slowdown to a user when exporting. 

Out of curiosity, I considered what a more "efficient" algorithm might look like (e.g. something `O(m log m)`, where `m` is the size of the counts hashmap), but it got _extremely_ convoluted. Any performance benefit isn't worth difficult-to-read code in this case, so I'm happy with the while-loop approach you have here.

My one request, though, is that you make sure to handle the case where a move ends mid-measure (where the end measure of one move _should_ be the start measure of the next). That shouldn't happen in 99% of cases, but it's safer to handle it in case someone - for some reason - ever needs it.

**Review by vdye — COMMENTED** [review]
Overall, I like the approach you have here (I originally thought it could be more efficient, but anything more efficient would be unnecessarily complex). 

I added some comments on the implementation details (including some possible bugs), but hopefully they won't be too difficult to fix. Once you push an updated version, I'll do some manual testing and report back on any issues I see (if any).

Thanks again for contributing these fixes!

**Comment by parker-rho** [comment]
Thank you for the comments I'll get these done after dinner.

> Unrelated: How do I request reviews on my PR's instead of manually @ing you @vdye?
Also is there a way to do this? I see that I can now re-request a review after you've made comments but I couldn't find it when I first made the pull request.

**Comment by vdye** [comment]
> > Unrelated: How do I request reviews on my PR's instead of manually @ing you @vdye?
> 
> Also is there a way to do this? I see that I can now re-request a review after you've made comments but I couldn't find it when I first made the pull request.

Ah sorry I forgot to respond to this! I think it was a lack of permissions - I've upgraded you to the "Triage" role, so you should now be able to assign yourself to PRs (if you want) and directly request me/anyone else as a reviewer. Let me know if you run into any other issues and I'll try to figure it out!

**Comment by parker-rho** [comment]
I tried my best fixing up the code. I tested as many cases as I could think of. Let me know if there was something I missed.

File: src/main/java/org/bigredbands/mb/controllers/PDFGenerator.java [hunk 2]
```diff
@@ -123,17 +125,23 @@ public void createPDF(DrillInfo drillInfo, File file) throws IOException {
...
-                contentStream.showText("Measures:  " + (begMeasure + 1)
-                        + " - " + endMeasure);
-            } else {
-                contentStream.showText("Measures:  " + begMeasure + " - "
-                        + endMeasure);
+            int totalCounts = extraCounts;
+            while (move.getCounts() > totalCounts){
+                if (drillInfo.getCountsHashMap().get(currentMeasure) != null) {
+                    currentCountsPerMeasure = drillInfo.getCountsHashMap().get(currentMeasure);
+                }
```
Comment (vdye) [inline src/main/java/org/bigredbands/mb/controllers/PDFGenerator.java:132]: I tested this with an drill file from a past year's show (where we inserted the drum feature as one _long_ measure), and noticed there was an off-by-one error in the measure numbers in the PDF. This change fixes it.

```suggestion
                currentCountsPerMeasure = drillInfo.getCountsHashMap().getOrDefault(currentMeasure + 1, currentCountsPerMeasure);
```

**Review by vdye — COMMENTED** [review]
Sorry for taking so long to review! I suggested one correction (based on an issue I found in my own testing), but otherwise everything seems to be working correctly.

File: src/main/java/org/bigredbands/mb/controllers/PDFGenerator.java (hunk 2 above)
Comment (parker-rho) [reply src/main/java/org/bigredbands/mb/controllers/PDFGenerator.java:132]: Sorry for not communicating this earlier but I went on vacation out of the country for 2 weeks. I'm back now and I'll get this change done asap. I hope you're doing well!

**Review by vdye — APPROVED** [review]
